"""
Agent graph — wires the LLM + tools into a ReAct loop using LangGraph.
"""
from langchain_groq import ChatGroq
from langgraph.prebuilt import create_react_agent

from agent.tools import make_tools
from config import GROQ_API_KEY, GROQ_MODEL

SYSTEM_PROMPT = """You are RepoMind, an expert assistant that answers questions about a \
specific GitHub codebase using the tools provided.

Rules:
- Always use search_codebase before answering, even if you think you know the answer.
- If the first search doesn't give enough context, use read_file to see the full file.
- Every answer MUST cite the specific file path and line numbers you used.
- If you genuinely cannot find relevant code after searching, say so plainly \
instead of guessing.
- Be concise. Answer like a senior engineer explaining to a teammate, not a textbook.
"""


def build_agent(repo_id: str, repo_path: str):
    llm = ChatGroq(api_key=GROQ_API_KEY, model=GROQ_MODEL, temperature=0)
    tools = make_tools(repo_id, repo_path)
    agent = create_react_agent(llm, tools, state_modifier=SYSTEM_PROMPT)
    return agent


def ask(repo_id: str, repo_path: str, question: str, max_retries: int = 3) -> dict:
    from groq import BadRequestError

    agent = build_agent(repo_id, repo_path)
    last_error = None
    for attempt in range(max_retries):
        try:
            result = agent.invoke({"messages": [{"role": "user", "content": question}]})
            messages = result["messages"]
            final_answer = messages[-1].content
            return {"answer": final_answer, "messages": messages}
        except BadRequestError as e:
            if "tool_use_failed" in str(e):
                last_error = e
                continue
            raise
    raise last_error


def ask_stream(repo_id: str, repo_path: str, question: str, max_retries: int = 3):
    """
    Generator that streams the final answer token by token.
    Yields strings: either text chunks or a special JSON citations line at the end.

    How it works:
    - agent.stream() with stream_mode="messages" gives us each message chunk
      as it's generated by the LLM
    - We only stream chunks from the final AI response (not tool call internals)
    - After streaming completes, we yield a citations payload so the frontend
      can render citation pills without a second request
    """
    import re
    import json
    from groq import BadRequestError
    from langchain_core.messages import AIMessageChunk

    agent = build_agent(repo_id, repo_path)
    last_error = None

    for attempt in range(max_retries):
        try:
            full_text = ""
            # stream_mode="messages" streams token by token from the LLM
            for chunk, metadata in agent.stream(
                {"messages": [{"role": "user", "content": question}]},
                stream_mode="messages",
            ):
                # Only yield actual AI text chunks, skip tool calls / tool results
                if (
                    isinstance(chunk, AIMessageChunk)
                    and chunk.content
                    and not chunk.additional_kwargs.get("tool_calls")
                ):
                    yield chunk.content
                    full_text += chunk.content

            # After full answer is streamed, extract citations and send as final event
            citations = []
            seen = set()
            for match in re.finditer(r"FILE: (.+?) \(lines (\d+)-(\d+)\)", full_text):
                file_path, start, end = match.group(1), int(match.group(2)), int(match.group(3))
                key = (file_path, start, end)
                if key not in seen:
                    seen.add(key)
                    citations.append({"file_path": file_path, "start_line": start, "end_line": end})

            # Special marker so frontend knows this is citations, not text
            yield f"\n__CITATIONS__{json.dumps(citations)}"
            return

        except BadRequestError as e:
            if "tool_use_failed" in str(e):
                last_error = e
                continue
            raise

    raise last_error
